"""empty message

Revision ID: 5fb207ccbdab
Revises: 812ce63d30d1
Create Date: 2018-03-28 14:07:13.097723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb207ccbdab'
down_revision = '812ce63d30d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computer', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('computer', 'name')
    # ### end Alembic commands ###
